ai:
  model_name: "buffalo_l"
  det_size: [480, 480]
  threshold: 0.65

camera:
  device_id: 0
  width: 1280
  height: 720
  fps: 30

database:
  db_type: "mysql"
  host: "127.0.0.1"
  port: 3309
  user: "root"
  password: "19082004"
  db_name: "ptit_diem_danh"
  images_dir: "./database/registered_images"
  encryption_key: "j9z1S0Hpx3D5D-zD5vQo_N_T5yP6yS1z4aB8c7D9eFg="

attendance:
  cooldown_seconds: 30
  log_file: "./logs/attendance_log.csv"

server:
  host: "127.0.0.1"
  port: 8000

liveness:
  enabled: false
