"""Add class_schedules

Revision ID: 11cde19eb194
Revises: b2996b480bba
Create Date: 2026-08-03 11:38:08.433111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11cde19eb194'
down_revision: Union[str, Sequence[str], None] = 'b2996b480bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_records')
    op.drop_table('class_sessions')
    op.add_column('class_schedules', sa.Column('room_id', sa.String(length=20), nullable=False))
    op.add_column('class_schedules', sa.Column('day_of_week', sa.Integer(), nullable=False))
    op.add_column('class_schedules', sa.Column('start_shift', sa.Integer(), nullable=False))
    op.add_column('class_schedules', sa.Column('end_shift', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'class_schedules', 'classrooms', ['room_id'], ['room_id'], ondelete='RESTRICT')
    op.drop_column('class_schedules', 'start_time')
    op.drop_column('class_schedules', 'room')
    op.drop_column('class_schedules', 'study_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_schedules', sa.Column('study_date', sa.DATE(), nullable=False))
    op.add_column('class_schedules', sa.Column('room', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('class_schedules', sa.Column('start_time', mysql.TIME(), nullable=False))
    op.drop_constraint(None, 'class_schedules', type_='foreignkey')
    op.drop_column('class_schedules', 'end_shift')
    op.drop_column('class_schedules', 'start_shift')
    op.drop_column('class_schedules', 'day_of_week')
    op.drop_column('class_schedules', 'room_id')
    op.create_table('attendance_records',
    sa.Column('record_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('recorded_at', mysql.DATETIME(), nullable=True),
    sa.Column('confidence_score', mysql.FLOAT(), nullable=True),
    sa.Column('proof_image_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('notes', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.session_id'], name=op.f('attendance_records_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('attendance_records_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['accounts.account_id'], name=op.f('attendance_records_ibfk_3'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('record_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uc_session_student'), 'attendance_records', ['session_id', 'student_id'], unique=True)
    op.create_table('class_sessions',
    sa.Column('session_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('room_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('session_date', sa.DATE(), nullable=False),
    sa.Column('shift', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=False),
    sa.Column('session_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('notes', mysql.VARCHAR(length=255), nullable=True),
    sa.CheckConstraint('(`end_time` > `start_time`)', name=op.f('chk_session_time')),
    sa.ForeignKeyConstraint(['class_id'], ['credit_classes.class_id'], name=op.f('class_sessions_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['classrooms.room_id'], name=op.f('class_sessions_ibfk_2'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uc_room_schedule'), 'class_sessions', ['room_id', 'session_date', 'shift'], unique=True)
    # ### end Alembic commands ###
