"""Sync DB with models

Revision ID: b2996b480bba
Revises: 
Create Date: 2026-08-03 10:12:13.071701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b2996b480bba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('student_class_enrollment')
    # op.drop_index(op.f('ix_attendance_histories_attendance_id'), table_name='attendance_histories')
    # op.drop_table('attendance_histories')
    # op.drop_index(op.f('ix_leave_requests_request_id'), table_name='leave_requests')
    # op.drop_table('leave_requests')
    # op.drop_index(op.f('ix_class_schedules_schedule_id'), table_name='class_schedules')
    # op.drop_table('class_schedules')
    op.alter_column('face_features', 'student_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('ix_face_features_feature_id'), table_name='face_features')
    op.drop_constraint(op.f('face_features_ibfk_1'), 'face_features', type_='foreignkey')
    op.create_foreign_key(None, 'face_features', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_lecturers_lecturer_id'), table_name='lecturers')
    op.alter_column('subjects', 'credits',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_subjects_subject_id'), table_name='subjects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subjects_subject_id'), 'subjects', ['subject_id'], unique=False)
    op.alter_column('subjects', 'credits',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_lecturers_lecturer_id'), 'lecturers', ['lecturer_id'], unique=False)
    op.drop_constraint(None, 'face_features', type_='foreignkey')
    op.create_foreign_key(op.f('face_features_ibfk_1'), 'face_features', 'students', ['student_id'], ['student_id'])
    op.create_index(op.f('ix_face_features_feature_id'), 'face_features', ['feature_id'], unique=False)
    op.alter_column('face_features', 'student_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.create_table('attendance_histories',
    sa.Column('attendance_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('schedule_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('confirmed_by', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['class_schedules.schedule_id'], name=op.f('attendance_histories_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('attendance_histories_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_attendance_histories_attendance_id'), 'attendance_histories', ['attendance_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('request_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('schedule_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.TEXT(), nullable=True),
    sa.Column('evidence', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('approved_by', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['class_schedules.schedule_id'], name=op.f('leave_requests_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('leave_requests_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_leave_requests_request_id'), 'leave_requests', ['request_id'], unique=False)
    op.create_table('class_schedules',
    sa.Column('schedule_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('study_date', sa.DATE(), nullable=False),
    sa.Column('room', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['credit_classes.class_id'], name=op.f('class_schedules_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_class_schedules_schedule_id'), 'class_schedules', ['schedule_id'], unique=False)
    op.create_table('student_class_enrollment',
    sa.Column('class_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('academic_status', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['credit_classes.class_id'], name=op.f('student_class_enrollment_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('student_class_enrollment_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'student_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
