services:
  mysql_db:
    image: mysql:8.0
    container_name: ptit_diem_danh_mysql
    restart: always
    environment:
      # Cấu hình y hệt máy của Nhật Huy
      MYSQL_ROOT_PASSWORD: "19082004"
      MYSQL_DATABASE: ptit_diem_danh
    ports:
      - "3309:3306" 
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

