
services:
  mysql_db:
    image: mysql:8.0
    container_name: ai_attendance_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ai_attendance_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - "3306:3306"
    volumes:
      # Ánh xạ thư mục chứa script SQL để tự động chạy khi khởi tạo container lần đầu
      - ./init:/docker-entrypoint-initdb.d
      # Mount volume lưu trữ data thực tế để data tồn tại (persistent)
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: